version: 2
jobs:
  build-arduino-default:
    machine: true
    steps:
      - checkout
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./.circleci/*.sh
      - run:
          name: Install
          command: ./.circleci/install_arduino.sh
      - run:
          name: Build
          command: ./.circleci/script_arduino.sh

workflows:
  version: 2
  build:
    jobs:
      - build-arduino-default
